import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from "next/router";
import BlogCard from '../../components/blogCards'
import styles from '../../styles/Home.module.css'
import image from "../../public/sunset.jpg";
import {AiOutlineTwitter} from 'react-icons/ai'
import {VscQuote} from 'react-icons/vsc'
import {VscSearch} from 'react-icons/vsc';
import RelatedPostCard from '../../components/relatedPosts';
import LatestNewsInfo from '../../components/latestNews';
import Newsletter from '../../components/newsletter';
import {useEffect, useState} from "react";
import Parser from 'html-react-parser';
import axios from "../../services/axiosService";

export default function Blogpost() {
    const [blogTitle, setBlogTitle] = useState("");
    const [blogAuthor, setBlogAuthor] = useState("");
    const [blogContent, setBlogContent] = useState("")
    const Router = useRouter();
    useEffect(() => {
        if (Router.query.id) {
            axios.get("/blog/" + Router.query.id).then(rawData => {
                let data = rawData.data.data;
                setBlogAuthor(data.blogAuthor);
                setBlogTitle(data.blogTitle);
                setBlogContent(convertDataToHtml(data.blogContent.blocks))
                document.getElementById("contentDisplay").innerHTML = convertDataToHtml(data.blogContent.blocks)
            })
        } else {
            // Router.push("/");
        }
    })

    return (
        <div className={styles.container}>
            <Head>
                <title>Blog app</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className='mx-20 px-10'>
                <section className='mt-3'>
                    <div className=''>
                        <div className={"font-montserrat font-bold text-[55px] text-center"}>
                            <h1 className={"text-4xl"}>
                                {blogTitle}
                            </h1>
                        </div>
                    </div>
                </section>
                <section className='flex mt-3 w-full space-x-4'>

                    <div className='w-full lg:w-2/3 px-4 py-4 leading-6 '>
                      <div id="contentDisplay" className={"space-y-4"}/>
                        <div className='hidden'>
                            <Image className='rounded-md' src={image} alt="Sunset in the mountains" width={866}
                                   height={473}/>
                            <div className={"font-sans font-normal text-[24px] text-justify leading-8 text-[#37404E]"}>
                                <p>
                                    Helping everyone live happier, healthier lives at home through their kitchen.
                                    Kitchen is a daily food magazine on the Web celebrating life in the kitchen through
                                    home cooking and kitchen intelligence.
                                </p>
                            </div>

                            <div className={"font-sans font-normal text-[18px] text-justify text-[#37404E] mt-2"}>
                                <p>
                                    This is a site for people who like to get their hands dirty while they cook.
                                    It is for those who care about the quality of their food, and how it affects the
                                    health of themselves and the planet.
                                    It is for cooks who care about
                                </p>
                            </div>

                            <div
                                className={"font-montserrat font-semibold text-[24px] text-justify leading-8 text-[#1F2938] mt-4"}>
                                <p>Lorem ipsum dolor sit amet cons</p>
                            </div>

                            <div className={"font-sans font-normal text-[18px] text-justify text-[#1F2938] mt-2"}>
                                <p>
                                    Tortor, lobortis semper viverra ac, molestie tortor laoreet amet euismod et diam
                                    quis aliquam consequat porttitor integer a nisl,
                                    in faucibm eros est amet turpis nunc in turpis massa et eget facilisis ante molestie
                                    penatibus dolor volutpat, porta pellentesque
                                    scelerisque at ornare dui tincidunt cras feugiat tempor lectus
                                </p>
                            </div>

                            <div className='flex mt-3 space-x-2'>
                                <div className=''>
                                    <Image className='rounded-md' src={image} alt="Sunset in the mountains" width={410}
                                           height={410}/>
                                </div>

                                <div>
                                    <Image className='rounded-md' src={image} alt="Sunset in the mountains" width={410}
                                           height={410}/>
                                </div>
                            </div>

                            <div
                                className={"font-sans font-normal  text-[18px] text-justify leading-6 text-[#37404E] mt-2"}>
                                <p>
                                    Sit quis semper sit sapien. Massa bibendum scelerisque metus phasellus semper sed.
                                    Enim, lacus faucibus aliquam id vitae a et pellentesque amet.
                                    Felis quam lacinia elementum arcu. Tempor ullamcorper donec sit arcu varius diam
                                    luctus ultrices
                                </p>
                            </div>

                            <div
                                className='bg-[#F5F5F5] px-12 py-12 my-4 mx-12 rounded-tr-3xl rounded-bl-3xl justify-center items-center relative'>
                                <div className='absolute top-0 left-0 px-4 py-4'>
                                    <VscQuote className='text-4xl text-center text-[#2B3D34] opacity-20'/>
                                </div>
                                <p className='font-sans font-normal text-[25px] leading-8 text-[#37404E]'>
                                    Et nisi, ut arcu nec enim fames facilisi justo, mi amet, vitae
                                    in vehicula a, id placerat consequat mauris non adipiscing in sed et dui tristique
                                    at amet, nunc
                                </p>
                                <div className='flex item-center text-[16px] mt-3'>
                                    <AiOutlineTwitter className='text-[#00ACEE]'/>
                                    <p className='font-lato font-normal  text-[#2B3D34] opacity-50'>
                                        Job Hub
                                    </p>
                                </div>
                            </div>

                            <div
                                className={"font-sans font-normal text-[18px] text-justify leading-6 text-[#37404E] mt-2"}>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet id enim, libero sit.
                                    Est donec lobortis cursus amet,
                                    cras elementum libero convallis feugiat.
                                    Nucilisi tincidunt a arcu, sem donec sed sed. Tincidunt morbi scelerisque lectus
                                    non. At leo mauris, vel augue. Facilisi diam
                                </p>
                            </div>

                            <div className="font-normal mt-4 text-[#1F2938] text-[14px] flex space-x-2">
                                <p className="px-3 py-1 border rounded-sm w-fit">Design</p>
                                <p className="px-3 py-1 border rounded-sm w-fit">Perspiciatis</p>
                            </div>
                        </div>

                        {/* Steve Job Card */}

                        <div className='px-8 py-8 border rounded-3xl mt-5 shadow-md'>
                            <div className='flex space-x-2'>
                                <div>
                                    <Image className='rounded-full' src={image} alt="Sunset in the mountains" width={64}
                                           height={64}/>
                                </div>
                                <div>
                                    <p className={"font-montserrat font-bold text-[20px] text-[#253D4E]"}>
                                      {blogAuthor}
                                    </p>
                                    <div className='flex font-sans font-normal text-[12px] text-[#A0ABB8] space-x-2'>
                                        <p>
                                            306 posts
                                        </p>
                                        <p>
                                            Since 2012
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div className='font-sans font-normal text-[18px] text-[#37404E] leading-6'>
                                <p>Hi there, I am a veteran food blogger sharing my daily all kinds of healthy and fresh
                                    recipes. I find inspiration in nature, on the streets and almost everywhere.
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet id enim, libero sit.
                                    Est donec lobortis cursus amet</p>
                            </div>
                        </div>

                        <div>
                            <p className='font-montserrat font-bold text-center text-[40px] my-8 text-[#253D4E]'>
                                Related Posts
                            </p>
                        </div>
                        <div className='grid grid-cols-3 gap-4'>
                            <RelatedPostCard/>
                            <RelatedPostCard/>
                            <RelatedPostCard/>
                        </div>
                        <div className='w-full'><Newsletter/></div>


                    </div>


                    <div className='w-1/3 px-4 py-4 space-y-12'>
                        <div className='px-2 py-2 border shadow-md rounded-lg flex items-center space-x-2'>
                            <VscSearch/>
                            <input type="text" placeholder='Search'/>
                        </div>
                        <div className='px-4 py-4 bg-[#f3fbfb] shadow-md border-blue-300'>
                            <div className=''>
                                <p className='text-[#1F2938] font-bold font-montserrat text-[22px]'>Catagory</p>
                                <div className='w-full border border-black'></div>
                            </div>


                            <div className='justify-between flex px-2 py-2 border-b-2 items-center'>
                                <p>Recruitment News</p>
                                <p className='px-2 py-1 rounded-lg border bg-[#EDEDEE]'> 28</p>
                            </div>

                            <div className='justify-between flex px-2 py-2 border-b-2 items-center'>
                                <p>Job Venues</p>
                                <p className='px-2 py-1 rounded-lg border bg-[#EDEDEE]'> 28</p>
                            </div>

                            <div className='justify-between flex px-2 py-2 border-b-2 items-center'>
                                <p>Job Tools</p>
                                <p className='px-2 py-1 rounded-lg border bg-[#EDEDEE]'> 28</p>
                            </div>

                            <div className='justify-between flex px-2 py-2 border-b-2 items-center'>
                                <p>Full Time Job</p>
                                <p className='px-2 py-1 rounded-lg border bg-[#EDEDEE]'> 28</p>
                            </div>

                        </div>

                        {/* Latest news card */}
                        <div className='px-4 py-4 shadow-md border border-blue-300 rounded-lg space-y-4'>
                            <div className=''>
                                <p className='text-[#1F2938] font-bold font-montserrat text-[22px]'>Latest News</p>
                                <div className='w-full border border-black'></div>
                            </div>

                            <LatestNewsInfo/>
                            <LatestNewsInfo/>
                            <LatestNewsInfo/>


                        </div>


                        {/* Popular tags */}
                        <div className='px-4 py-4 rounded-lg border border-gray-400 shadow-md'>
                            <div className=''>
                                <p className='text-[#1F2938] font-bold font-montserrat text-[22px]'>Popular Tags</p>
                                <div className='w-full border border-blue'></div>
                            </div>
                            <div className='font-sans text-[14px] font-normal text-[#727272]'>
                                <p className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 mr-3 mt-2">Figma</p>
                                <p className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 mr-3 mt-2">Adobe XD</p>
                                <p className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 mr-3 mt-2">PSD</p>
                            </div>

                            <div className='font-sans text-[14px] font-normal text-[#727272]'>
                                <p className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 mr-3 mt-2">Employer</p>
                                <p className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 mr-3 mt-2">Recruiting</p>
                                <p className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 mr-3 mt-2">Work</p>
                            </div>

                        </div>
                    </div>
                </section>


            </main>
        </div>
    )
}

function convertDataToHtml(blocks) {
    let convertedHtml = "";
    blocks.map(block => {
        switch (block.type) {
            case "header":
                convertedHtml += `<h${block.data.level} style="margin: 10px">${block.data.text}</h${block.data.level}>`;
                break;
            case "embded":
                convertedHtml += `<div><iframe width="560" height="315" src="${block.data.embed}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>`;
                break;
            case "paragraph":
                convertedHtml += `<p style="text-align: ${block.data.alignment}; margin: 10px">${Parser(block.data.text)}</p>`;
                break;
            case "delimiter":
                convertedHtml += "<hr />";
                break;
            case "image":
                convertedHtml += `<div style="display: flex; class="${block.data.withBackground ? 'inline-image__picture--withBackground' : ''}" justify-content: center"><img style="text-align: center; width: 100%; object-fit: contain; max-height: 400px" class="img-fluid" src="${block.data.url}" title="${block.data.caption}"  alt="image"/></div><p style="text-align: center">${block.data.caption}</p>`;
                break;
            case "list":
                if (block.data.style === "unordered") {
                    convertedHtml += "<ul class='cdx-list__item cdx-list--unordered'>";
                    block.data.items.forEach(function (li) {
                        convertedHtml += `<li>${li}</li>`;
                    });
                    convertedHtml += "</ul>";
                } else if (block.data.style === "ordered") {
                    convertedHtml += "<ol class='cdx-list__item cdx-list--ordered'>";
                    block.data.items.forEach(function (li) {
                        convertedHtml += `<li>${li}</li>`;
                    });
                    convertedHtml += "</ol>";
                }
                break;
            case "raw":
                convertedHtml += Parser(block.data.html);
                break;
            default:
                console.log("Unknown block type", block.type);
                break;
        }
    });
    return convertedHtml;
}
