import Head from 'next/head'
import { firestore } from "../../services/firebaseService";
import ProjectCard from '../../components/projectComponents/projectCard'
import styles from '../../styles/Home.module.css'
import { useEffect, useState } from "react";

export default function Home() {
  const [projects, setProjects] = useState([]);
  const [isInit, setIsInit] = useState(false);
  useEffect(() => {
    if(!isInit) {
      firestore.collection("projects").get().then((querySnapshot) => {
        let newPortfolios = [];
        querySnapshot.forEach((doc) => {
          newPortfolios.push({...doc.data(), id: doc.id})
        });
        setProjects(newPortfolios)
      });
      setIsInit(true);
    }
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Projects that I have developed
        </h1>
        <h2 className={styles.subTitle}>
          Welcome to our Projects
        </h2>

        <div className="px-5 pt-4 pb-2">
             <span className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">Recruitment</span>
             <span className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">Branding</span>
             <span className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">Workplace</span>
             <span className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">Job Tips</span>
             <span className="inline-block bg-[#f3fbfb] rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">Contributors</span>
        </div>

        <div className="grid grid-cols-3 gap-3">
          {projects.sort().map((item) => {
            return(
                <div className='mt-5' key={item.id}>
                  <ProjectCard
                      title={item.title}
                      image={process.env.NextBasePath + "/sunset.jpg"}
                      description={"by: " + item.author}
                      id={item.id}
                  />
                </div>
            )
          })}
        </div>

          <div className="flex justify-center mt-8">
              <div className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">1</div>
              <div className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">2</div>
              <div className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">3</div>
              <div className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">4</div>
              <div className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">5</div>
              <div className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-3 mb-2">6</div>

          </div>
      </main>
    </div>
  )
}
