import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ammar Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Ammar Portfolio Website
        </h1>

        <p className={styles.description}>
          Under Construction xD (TM)
        </p>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
